swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: ShipperAPI Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: shipper
    description: Shipper
paths:
  /home:
    get:
      tags:
        - shipper
      summary: home
      operationId: homeUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /shipper:
    get:
      tags:
        - shipper
      summary: getShippers
      operationId: getShippersUsingGET
      produces:
        - '*/*'
      parameters:
        - name: approved
          in: query
          description: approved
          required: false
          type: boolean
        - name: pageNo
          in: query
          description: pageNo
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Shipper'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - shipper
      summary: addShipper
      operationId: addShipperUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: loadShipper
          description: loadShipper
          required: true
          schema:
            $ref: '#/definitions/LoadShipper'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ShipperCreateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/shipper/{id}':
    get:
      tags:
        - shipper
      summary: getOneShipper
      operationId: getOneShipperUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Shipper'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - shipper
      summary: updateShipper
      operationId: updateShipperUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
        - in: body
          name: loadShipper
          description: loadShipper
          required: true
          schema:
            $ref: '#/definitions/LoadShipper'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ShipperUpdateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - shipper
      summary: deleteShipper
      operationId: deleteShipperUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ShipperDeleteResponse'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  LoadShipper:
    type: object
    properties:
      approved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      name:
        type: string
      phoneNo:
        type: integer
        format: int64
    title: LoadShipper
  Shipper:
    type: object
    properties:
      approved:
        type: boolean
      companyName:
        type: string
      id:
        type: string
      kyc:
        type: string
      name:
        type: string
      phoneNo:
        type: integer
        format: int64
    title: Shipper
  ShipperCreateResponse:
    type: object
    properties:
      message:
        type: string
      status:
        type: string
    title: ShipperCreateResponse
  ShipperDeleteResponse:
    type: object
    properties:
      message:
        type: string
      status:
        type: string
    title: ShipperDeleteResponse
  ShipperUpdateResponse:
    type: object
    properties:
      message:
        type: string
      status:
        type: string
    title: ShipperUpdateResponse
